// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ServiceContext))]
    partial class ServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.DetallesCompras", b =>
                {
                    b.Property<int>("Id_DetallesCompras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_DetallesCompras"));

                    b.Property<int?>("ComprasId_Compras")
                        .HasColumnType("int");

                    b.Property<int>("IdCompras")
                        .HasColumnType("int");

                    b.Property<int>("IdProductos")
                        .HasColumnType("int");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<int>("Precio_Total")
                        .HasColumnType("int");

                    b.Property<int?>("ProductosIdProductos")
                        .HasColumnType("int");

                    b.HasKey("Id_DetallesCompras");

                    b.HasIndex("ComprasId_Compras");

                    b.HasIndex("ProductosIdProductos");

                    b.ToTable("DetallesCompras", (string)null);
                });

            modelBuilder.Entity("Entities.Entities.Categoria", b =>
                {
                    b.Property<int>("Id_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Categoria"));

                    b.Property<string>("Nombre_Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Categoria");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("Entities.Entities.Compras", b =>
                {
                    b.Property<int>("Id_Compras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Compras"));

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id_Compras");

                    b.HasIndex("UsuarioId_Usuario");

                    b.ToTable("Compras", (string)null);
                });

            modelBuilder.Entity("Entities.Entities.Productos", b =>
                {
                    b.Property<int>("IdProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductos"));

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int");

                    b.Property<int>("IdTipos")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProductos");

                    b.HasIndex("IdSolicitud");

                    b.HasIndex("IdTipos");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("Entities.Entities.Roll", b =>
                {
                    b.Property<int>("IdRoll")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoll"));

                    b.Property<string>("Nombre_Roll")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRoll");

                    b.ToTable("Roll", (string)null);
                });

            modelBuilder.Entity("Entities.Entities.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Apellidos_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRoll")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("IdRoll");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Entities.Solicitud", b =>
                {
                    b.Property<int>("Id_Solicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Solicitud"));

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Solicitud");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Solicitud", (string)null);
                });

            modelBuilder.Entity("Entities.Tipos", b =>
                {
                    b.Property<int>("IdTipos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipos"));

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipos");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Tipos", (string)null);
                });

            modelBuilder.Entity("Entities.DetallesCompras", b =>
                {
                    b.HasOne("Entities.Entities.Compras", null)
                        .WithMany("DetallesCompras")
                        .HasForeignKey("ComprasId_Compras");

                    b.HasOne("Entities.Entities.Productos", null)
                        .WithMany("DetallesCompras")
                        .HasForeignKey("ProductosIdProductos");
                });

            modelBuilder.Entity("Entities.Entities.Compras", b =>
                {
                    b.HasOne("Entities.Entities.Usuario", null)
                        .WithMany("compras")
                        .HasForeignKey("UsuarioId_Usuario");
                });

            modelBuilder.Entity("Entities.Entities.Productos", b =>
                {
                    b.HasOne("Entities.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Tipos", "Tipos")
                        .WithMany("Productos")
                        .HasForeignKey("IdTipos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Tipos");
                });

            modelBuilder.Entity("Entities.Entities.Usuario", b =>
                {
                    b.HasOne("Entities.Entities.Roll", "Roll")
                        .WithMany()
                        .HasForeignKey("IdRoll")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roll");
                });

            modelBuilder.Entity("Entities.Solicitud", b =>
                {
                    b.HasOne("Entities.Entities.Usuario", "Usuario")
                        .WithMany("Solicitud")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Tipos", b =>
                {
                    b.HasOne("Entities.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Entities.Entities.Compras", b =>
                {
                    b.Navigation("DetallesCompras");
                });

            modelBuilder.Entity("Entities.Entities.Productos", b =>
                {
                    b.Navigation("DetallesCompras");
                });

            modelBuilder.Entity("Entities.Entities.Usuario", b =>
                {
                    b.Navigation("Solicitud");

                    b.Navigation("compras");
                });

            modelBuilder.Entity("Entities.Tipos", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
